# Welcome to Jekyll!
#

# Site settings
title: Ian "Ace" Rodgers, PI
description: |
  Happy Birthday Ian!
  We hope that this website brings you lots of joy  
  Love, Hannah and Tim
owner: Ian Rodgers # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acerodgers.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/kleixa
  github: https://github.com/acerodgers
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/Ian.Mainrod
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
